saveExact: true
overrides:
  # Vulnerability Fixes
  esbuild: ">=0.24.3"
allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - "@rimelight/cms@0.0.2"
  - "@rimelight/config@0.0.2"
